/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.maxkatz.queenssolver;

public class App {
    public String getGreeting() {
        return "Hello world.  Inside App.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        System.out.println("In App");
    }
}
