/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.maxkatz.queenssolver;

public class Board {
    public int size;
    private int[] rows;
    private int[] cols;
    private int[] mains;
    private int[] antis;
    private Coords[] queens;
    
    public Board(int size) {
        // Set size and initialize properties
        this.size = size;
        this.rows = new int[size];
        this.cols = new int[size];
        this.mains = new int[size];
        this.antis = new int[size];
        this.queens = new Coords[size];
        for(int i = 0; i < size; i++) {
            this.rows[i] = 0;
            this.cols[i] = 0;
            this.mains[i] = 0;
            this.antis[i] = 0;
            this.queens[i] = null;
        }
    }
    
    public String toString() {
        /*
        // Using StringUtils from Apache commons
        String row = StringUtils.repeat(". ", this.size - 1) + ".\n";
        String board = StringUtils.repeat(row, this.size);
        */
        String board = "";
        return board;
    }
}

