/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.maxkatz.queenssolver;

public class Coords {
    int x;
    int y;
    
    public Coords(int x, int y) {
        this.x = x;
        this.y = y;
    }
    
    public Coords(Coords fromCoords) {
        this.x = fromCoords.x;
        this.y = fromCoords.y;
    }
}

