/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.maxkatz.queenssolver;

public class QueensSolver {
    public String getGreeting() {
        return "Hello world.  Inside QueensSolver.";
    }

    public static void main(String[] args) {
        System.out.println(new Board(8));
        System.out.println("Done.");
    }
}

